spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shorturl_db
      #authentication-database: admin
      #username: mongoadmin
      #password: password
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true