spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shorturl_db
      #authentication-database: admin
      #username: root
      #password: password
      #auto-index-creation: true

shorturl:
  service:
    baseurl: ${BASE_URL:http://localhost:8080/} # BASE_URL can be input as Environment Variable in Docker run. Default value is http://localhost:8080