spring:
  application:
    name: shorturl
  version: ${project.version}
  profiles:
    active: prod

shorturl:
  service:
    baseurl: ${BASE_URL:http://localhost:8080/} # BASE_URL can be input as Environment Variable in Docker run. Default value is http://localhost:8080
    allowallurls: ${ALLOW_ALL_URLS:false}  # ALLOW_ALL_URLS is an Environment Variable. It will set whether to allow shortening all URLs or only allowed Domains.
    defaultredirecturl: ${DEFAULT_REDIRECT_URL:https://github.com/thilankapathum/}
    defaultredirect: ${DEFAULT_REDIRECT:false}
    jwt-secret: ${JWT_SECRET:dfa2740015423f40da7388b4abed8adcd2c89e4e3b31a70ebbe59d1537d7aa2f3061fc8df5b2ff5ebac2b29a470c9e1fae9f7c42b91de951850c32a47d9a3111}
    jwt-expiration: ${JWT_EXPIRATION:120}
    verification-token-expiration: ${VERIFICATION_TOKEN_EXPIRE:15}