name: Deploy Spring-boot App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -Dskiptests --file ./backend/pom.xml

# BUILD DOCKER IMAGE. ATTENTION TO VERSION
      - name: Docker build
        run: docker buildx build --platform linux/amd64 -t thilankapathum/shorturl:0.0.4-aws .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

# PUSH DOCKER IMAGE TO DOCKER-HUB.
      - name: Push Docker Image
        run: docker push thilankapathum/shorturl:0.0.4-aws

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          port: 22
          script: |
              docker stop shorturl-backend-v3 || true
              docker rm shorturl-backend-v3 || true
              docker rmi shorturl-backend-v3 || true
              docker pull thilankapathum/shorturl:0.0.4-aws
            
              docker run -d --name shorturl-backend-4 \ 
              -e BASE_URL=${{ secrets.BASE_URL }} \
              -e DEFAULT_REDIRECT_URL=${{ secrets.DEFAULT_REDIRECT_URL }} \
              -e DEFAULT_REDIRECT=${{ secrets.DEFAULT_REDIRECT }} \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              -e JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }} \
              -e SPRING_DATA_MONGODB_HOST=${{ secrets.DB_HOST }} \
              -e SPRING_DATA_MONGODB_PORT=${{ secrets.DB_PORT }} \
              -e SPRING_DATA_MONGODB_USERNAME=${{ secrets.DB_USERNAME }} \
              -e SPRING_DATA_MONGODB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -e SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=${{ secrets.DB_AUTH_DATABASE }} \
              -e ALLOW_ALL_URLS=${{ secrets.ALLOW_ALL_URLS }} \
              -e SERVER_PORT=${{ secrets.SERVER_PORT }} \
              -e SERVER_SSL_KEY_STORE=${{ secrets.SERVER_SSL_KEY_STORE }} \
              -e SERVER_SSL_KEY_STORE_PASSWORD=${{ secrets.SERVER_SSL_KEY_STORE_PASSWORD }} \
              -e SERVER_SSL_KEY_STORE_TYPE=${{ secrets.SERVER_SSL_KEY_STORE_TYPE }} \
              -e SERVER_SSL_KEY_ALIAS=${{ secrets.SERVER_SSL_KEY_ALIAS }} \
              -v /root/keystore.jks:/keystore.jks \
              -p 443:443 --net shorturl-net thilankapathum/shorturl:0.0.4-aws